name: Genius AI Release Deploy
on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/geniuschatbots
  TARGET_SSH_HOST: ${{ secrets.TARGET_SSH_HOST }}
  TARGET_SSH_USER: ${{ secrets.TARGET_SSH_USER }}
  TARGET_SSH_PASSWORD: ${{ secrets.TARGET_SSH_PASSWORD }}
  TARGET_SSH_PORT: ${{ secrets.TARGET_SSH_PORT }}
  TARGET_SERVICE_PORT: 23501
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
  STREAMLIT_CONFIG: ${{ secrets.STREAMLIT_CONFIG }}
  LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
  LANGCHAIN_TRACING_V2: true
  LANGCHAIN_PROJECT: GeniusAIRelease

jobs:
  build-and-push-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      packages: write
      attestations: write
    outputs:
      output_image_tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Write streamlit config
        run: |
          mkdir GeniusChatbots/.streamlit
          echo "${{ env.STREAMLIT_CONFIG }}" > GeniusChatbots/.streamlit/config.yaml
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: GeniusChatbots
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    name: deploy to server
    runs-on: ubuntu-latest
    environment: release
    needs: build-and-push-image
    permissions:
      contents: read
      packages: write
      attestations: write
    steps: 
      - name: deploying
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ env.TARGET_SSH_HOST }}
          username: ${{ env.TARGET_SSH_USER }}
          password: ${{ env.TARGET_SSH_PASSWORD }}
          port: ${{ env.TARGET_SSH_PORT }}
          script: |
            docker container stop geniusai
            docker container rm geniusai
            docker container run -d --name geniusai -p ${{ env.TARGET_SERVICE_PORT }}:8501 -e OPENAI_API_KEY=${{ env.OPENAI_API_KEY }} -e TAVILY_API_KEY=${{ env.TAVILY_API_KEY }} -e LANGCHAIN_API_KEY=${{ env.LANGCHAIN_API_KEY }} -e LANGCHAIN_TRACING_V2=${{ env.LANGCHAIN_TRACING_V2 }} -e LANGCHAIN_PROJECT=${{ env.LANGCHAIN_PROJECT }} ${{needs.build-and-push-image.outputs.output_image_tags}}


      